name: Deploy JSON Server to GitHub Pages

on:
  push:
    branches:
      - main

# Keep these permissions
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install -g json-server jq

      - name: Generate static JSON files
        run: |
          mkdir -p public/api
          cp db.json public/
          touch public/.nojekyll
          
          # Generate courses endpoint
          jq '.courses' db.json > public/api/courses.json
          
          # Generate course-specific quiz endpoints
          mkdir -p public/api/courses
          jq '.courses[] | .id' db.json -r | while read -r courseId; do
            mkdir -p public/api/courses/$courseId
            jq ".quizzes | map(select(.courseId == \"$courseId\"))" db.json > public/api/courses/$courseId/quizzes.json
          done
          
          # Generate individual quiz endpoints
          mkdir -p public/api/quizzes
          jq '.quizzes[] | .id' db.json -r | while read -r quizId; do
            jq ".quizzes[] | select(.id == \"$quizId\")" db.json > public/api/quizzes/$quizId.json
          done
          
          # Create index.html with links to API endpoints
          echo '<!DOCTYPE html>
          <html>
          <head>
            <title>MiniApp API</title>
          </head>
          <body>
            <h1>MiniApp API</h1>
            <p>Available API endpoints:</p>
            <ul>
              <li><a href="api/courses.json">Courses</a></li>
              <li>Course quizzes: <code>/api/courses/{courseId}/quizzes.json</code></li>
              <li>Individual quiz: <code>/api/quizzes/{quizId}.json</code></li>
            </ul>
          </body>
          </html>' > public/index.html

      - name: Debug information
        run: |
          echo "Current directory structure:"
          find public -type f | sort

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public # The folder to deploy
          branch: gh-pages # The branch to deploy to
          clean: true # Automatically remove deleted files from the deploy branch